name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test Move Grammar
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest
        ]

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run parse-examples
